### ISSUE TITLE
Extend functionality to include all running applications

### ISSUE THREAD

**Issue by georgeteo** [apaszke/termtile#1]
I don't have any applescript experience, but I was wondering if it was possible to extend the functionality to include resizing all running applications. I was thinking something along the lines of ps -ax | grep /Application/<name> integrated with what you have written. But I don't know applescript, so I don't actually know how you've implemented the window resizing.

**Comment by apaszke** [comment]
I was thinking about extending the script to different applications, and I'll probably do this in the future. However, it would require adding more arguments, so it wouldn't be as convenient. I don't really get what you meant by saying:

> I was thinking something along the lines of ps -ax | grep /Application/ integrated with what you have written

Could you please explain? Why would you resize all applications at the same time?

**Comment by AntoineAugusti** [comment]
An app worth looking at that is doing this http://spectacleapp.com

**Comment by danielcorin** [comment]
If you are willing to do a bit more setup, [Hammerspoon](http://www.hammerspoon.org/go/#winresize) lets you to write Lua code to control the OS and allows hotkey bindings. You can replicate all the functionality that Spectacle provides and much more.

You also might consider using Javascript Automation for OS X. [This walkthrough](https://robbycolvin.com/javascript-automation-in-os-x-yosemite/) is a nice place to start and here are the [docs](https://developer.apple.com/library/prerelease/mac/releasenotes/InterapplicationCommunication/RN-JavaScriptForAutomation/Articles/OSX10-10.html#//apple_ref/doc/uid/TP40014508-CH109-SW1) from Apple.

**Comment by apaszke** [comment]
I'm not that eager to use it for different applications, because it isn't it's initial purpose. I created this script just to be able to resize the terminal windows with simple commands, and not add any more global keyboard shortcuts. If you want to have a universal support it's probably best to stick to something else. I'm wondering if it makes sense to create just another one window manager. Are there any features that you're missing in these that already exist?
